import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Providers from './Providers'
import Trending from '@/components/Trending'
import SearchItem from '@/components/SearchItem'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <Trending
            topTrending="/top-trending"
            trending="Trending"
            rated="Top Rated"
            topRated="/top-rated"
          />
          <SearchItem name="Search Keywords..." search="Search" />
          {children}
        </Providers>
      </body>
    </html>
  )
}
